baseURL = "http://fadhil.web.id/"
languageCode = "en-us"
publishDir= ""
title = "Fadhil Imam | Personal Web"
theme = "hugo-lodi-theme"
# googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    # head theme color
    theme_color = "#E53935"

    # head description
    # This is what appears on the preview when posting this site on Facebook for example
    description = "Fadhil's Personal Website. You can kindly show all my works here, thanks!"

    # head photo
    # This is what appears on the preview when posting this site on Facebook for example
    description_photo = "portfolio.jpg"

    # favicon image (512x512px), place this in the static/img folder
    favicon = "favicon.png"

    # logo image (204x204px), place this in the static/img folder
    # this appears on the top left of the navigation
    logo = "logo.png"

    # Email
    email = "fadhilimamk@gmail.com"

    # Facebook username
    facebook = "fadhilimamkurnia"

    # Twitter username
    twitter = "fadhilimamk"

    # Dribbble username
    # dribbble = ""

    # LinkedIn URL
    linkedin = "https://www.linkedin.com/in/fadhilimamk/"
    
    # Medium username
    # medium = "asdf"

[params.nav]
    enable = true

[params.hero]
    enable = true
    
    # Place this image in the static/img folder
    avatar = "profil.jpg"
    subtitle = "Hi! I'm Fadhil, an enthusiastic person in technology and design."

    # Each element in this array makes a new <p> tag
    # You can write this text in markdown
    hero_right = [
    "**Currently an informatics/ computer sience undergraduate student at Institut Teknologi Bandung (ITB). Focusing on software development and systems, and I expect to graduate in 2019. Aamiin...**.",
    "For me, the highest achivement of a programmer is when they can make an app/ tool that can solve a real problem. So previously I also made some app to ease people doing their jobs. Please see my [Portofolio](#) to know more about them, or you can also visit my [GitHub](https://github.com/fadhilimamk). It's pretty cool.",
    "I do a bit of writing as well. Some of my articles can be read on my [Wordpress Blog](#). Its about my opinion and also some random things.",
    "Since on high school, I start to do some research activity, mainly on software development. I also won some research/ project competition back then. On collage, I start to do more advance research on computer science (distributed systems and storage). Hope to publish my first international paper soon. Bismillah :D",
    "",
    "terbentur, terbentur, terbentuk."]

    # Link to your resume, place your PDF in the /static folder
    resume = "resume.pdf"

[params.process]
    enable = true
    title = "My Activities"
    subtitle = ""

[params.case_studies]
    enable = true
    title = "Portofolio"
    subtitle = "Selected works"

[params.footer]
    enable = true
